import { db } from "@evoly/db";
import { z } from "zod";

export const createTicketTypeSchema = z.object({
  name: z.string().min(1).max(100),
  description: z.string().optional(),
  priceCents: z.number().int().min(0),
  currency: z.string().default("EUR"),
  quantity: z.number().int().min(1).optional(),
  saleStartsAt: z.coerce.date().optional(),
  saleEndsAt: z.coerce.date().optional(),
  minPerOrder: z.number().int().min(1).default(1),
  maxPerOrder: z.number().int().min(1).max(100).default(10),
  isNominative: z.boolean().default(false),
  customFields: z
    .array(
      z.object({
        label: z.string(),
        type: z.enum(["text", "textarea", "select", "checkbox", "number"]),
        required: z.boolean(),
        options: z.array(z.string()).optional(), // for select
      })
    )
    .optional(),
  seatingCategoryId: z.string().optional(),
});

export type CreateTicketTypeInput = z.infer<typeof createTicketTypeSchema>;

/**
 * Generate a unique QR code for a ticket.
 * Uses cuid internally, but can be overridden for testing.
 */
export function generateQrCode(): string {
  // cuid is generated by Prisma @default(cuid()), but we expose this for tests
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 9);
  return `evt-${timestamp}-${random}`;
}

/**
 * Check if a ticket type has available stock.
 */
export async function hasAvailableStock(
  ticketTypeId: string,
  requestedQuantity: number
): Promise<boolean> {
  const ticketType = await db.ticketType.findUnique({
    where: { id: ticketTypeId },
    select: { quantity: true, quantitySold: true },
  });

  if (!ticketType) return false;
  if (ticketType.quantity === null) return true; // unlimited

  return ticketType.quantity - ticketType.quantitySold >= requestedQuantity;
}

/**
 * Reserve stock temporarily (10 min) when order is created.
 * The actual decrement happens here — release happens if payment fails/expires.
 */
export async function reserveStock(
  ticketTypeId: string,
  quantity: number
): Promise<void> {
  await db.ticketType.update({
    where: { id: ticketTypeId },
    data: {
      quantitySold: { increment: quantity },
    },
  });
}

/**
 * Release reserved stock when order expires or payment fails.
 */
export async function releaseStock(
  ticketTypeId: string,
  quantity: number
): Promise<void> {
  await db.ticketType.update({
    where: { id: ticketTypeId },
    data: {
      quantitySold: { decrement: quantity },
    },
  });
}
